---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-lab-remotefetch-deployment
  labels:
    app: k8s-lab-remotefetch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-lab-remotefetch
  template:
    metadata:
      labels:
        app: k8s-lab-remotefetch
    spec:
      containers:
        - name: webapp
          image: localhost:5000/k8s-lab-multisvc:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: MODE
              value: remote-fetch
            - name: SERVICE_ADDRESS
              value: http://localhost:8001
          ports:
            - containerPort: 8000
        - name: timeapp
          image: localhost:5000/k8s-lab-multisvc:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: LISTEN_ADDRESS 
              value: 127.0.0.1:8001
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-lab-remotefetch
spec:
  selector:
    app: k8s-lab-remotefetch
  ports:
    - port: 8000
      targetPort: 8000
      name: webapp
  type: NodePort
